### PR TITLE
Feat: Styles for currently selected category

### LINKED ISSUE #133: [FEATURE]: Active Category Option
As a user, I want to recognize which category I am viewing.

- Create visual distinction for the active category in the options (see screenshot). Perhaps fill the active option pill and invert the text?
- Please make sure the active state follow accessibility best practices
- Make sure to test "all", usually that route requires special attention to not create unintended behavior.
- Perhaps make "all" capitalized (ex: "All") since all the other categories start with a capitalized letter
- I noticed the title of the page is the category, so maybe messaround with this? The title is not capitalized, so it may be better to be consistent with capitalization of both

SCR-20240516-mizt

### PR DESCRIPTION
**Pull request by jamesqquick**
## Description
Added styles for the currently selected category by inspecting the url path

## Issue
Closes #133 
## Screenshot

CleanShot 2024-06-07 at 09 49 14

## PR Requirements

- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [x] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

**Comment by mhuggins7278** [comment]
Did you intentionally have the ------ divider only the all category?
It results in some pretty jarring layout shift we swapping from all to one of the other categories and back. 

image

vs

image

**Comment by mhuggins7278** [comment]
Still some horizontal shift. 

horizontalShift

**Comment by jamesqquick** [comment]
@mhuggins7278 That should just be because of the scrollbar. I don't know if there's a way to fix that unfortunately

**Review by mhuggins7278 — APPROVED** [review]

**Review by chris-nowicki — APPROVED** [review]
Looks good to me!

**Pull request merged**
