### PR TITLE
chore: add .env.example

### PR DESCRIPTION
**Pull request by brwmaster**
## Description

When this PR gets merged there is a `.env.example` available so other contributors can see what they need to run the project locally 

## Solves

Solves [issue #15](https://github.com/Learn-Build-Teach/deals-for-devs/issues/15)

### CODE REVIEW

**Comment by chris-nowicki** [comment]
@brwmaster this is a great! There is only one issue I see in here with the domain being using in the from email.

`FROM_EMAIL='Deals for Devs<hello@dealsfordevs.com>'`

@jamesqquick Resend won't send this because developers working on anything regarding sending emails / email teamplates need to setup their own resend account.  If they don't have dealsfordevs.com verified in their accounts (which they shouldn't) resend block emails going out from that domain.

It looks like verifying a domain is required:
CleanShot 2024-03-05 at 23 55 38

not sure how we want to handle this.

**Comment by brwmaster** [comment]
@chris-nowicki Thanks for the feedback.

That is indeed a issue I never thought about mainly because I have never had this issue before but you make a real good point here. Maybe @jamesqquick has an idea?

**Review by jamesqquick — CHANGES_REQUESTED** [review]
This is awesome! Can you add one more for the Sentry DSN? This is an optional one but one we forgot to reference.

`NEXT_PUBLIC_SENTRY_DSN`

**Comment by brwmaster** [comment]
> This is awesome! Can you add one more for the Sentry DSN? This is an optional one but one we forgot to reference.
> 
> `NEXT_PUBLIC_SENTRY_DSN`

Added the sentry_dsn and also changed the main branch to the dev branch 😄

**Review by jamesqquick — APPROVED** [review]

**Comment by jamesqquick** [comment]
@all-contributors please add @brwmaster for code

**Pull request merged**
