### PR TITLE
docs: add contributors section

### LINKED ISSUE #11: Add All Contributors Bot to README or CONTRIBUTE markdown files
Use the bot from https://allcontributors.org/

This will add automated contributor cards to the repo based on their contribution: bug, features, etc..

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR adds the Contributors section to the READMe file

## Issue
Closes #11

### CODE REVIEW

**Review by jamesqquick — APPROVED** [review]

**Comment by CBID2** [comment]
I think you have to merge it @jamesqquick

**Comment by jamesqquick** [comment]
@CBID2 One note. I updated the target branch to `dev`. We'll push all ongoing changes there first. Then, progress to `staging` and `main` eventually.

**Comment by CBID2** [comment]
> @CBID2 One note. I updated the target branch to `dev`. We'll push all ongoing changes there first. Then, progress to `staging` and `main` eventually.

Ok got it

**Comment by CBID2** [comment]
@all-contributors please add @CBID2 for docs

**Pull request merged**
