### PR TITLE
feat: add a link to issues section on GitHub in the footer

### LINKED ISSUE #190: [FEATURE]: Add a Report an Issue Link to Github
As a visitor, I'd like to see a link in the footer of the app to be able to create an issue in Github to report a problem or feature request.

### PR DESCRIPTION
**Pull request by CBID2**
## Description

This PR adds a link to the issues section of this project's repository, making it easier for people to raise issues if they want a new feature or encounter a bug 
## Issue

Closes #190 
## PR Requirements

- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [x] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

**Review by ryandotfurrer — CHANGES_REQUESTED** [review]
Can you provide a screenshot of this across various screen sizes? Or a video works.

**Comment by CBID2** [comment]
> Can you provide a screenshot of this across various screen sizes? Or a video works.

I can't deploy it locally at the moment. Can you authorize the deployment on Netlify @ryandotfurrer? I can test it there

**Comment by ryandotfurrer** [comment]
> > Can you provide a screenshot of this across various screen sizes? Or a video works.
> 
> I can't deploy it locally at the moment. Can you authorize the deployment on ~~Netlify~~ Vercel @ryandotfurrer? I can test it there

@CBID2 I cannot, I don't have that power on Vercel, unfortunately. Why can't you develop it locally? I can pull your branch tm night to take a look at it.

**Comment by CBID2** [comment]
> > > Can you provide a screenshot of this across various screen sizes? Or a video works.
> 
> > 
> 
> > I can't deploy it locally at the moment. Can you authorize the deployment on ~~Netlify~~ Vercel @ryandotfurrer? I can test it there
> 
> 
> 
> @CBID2 I cannot, I don't have that power on Vercel, unfortunately. Why can't you develop it locally? I can pull your branch tm night to take a look at it.

Probably have to do with Xata @ryandotfurrer. I never finished setting it up after the creating the API. You can still check out my PR on your branch though

**Review by jamesqquick — CHANGES_REQUESTED** [review]
Can we move this under the "built with logos". It is also showing very large.

CleanShot 2024-06-15 at 08 13 14


Lastly, can we give it a slightly muted color. Let's use the same color from the giveaways section `text-white/70`

**Pull request closed without merging**
