### PR TITLE
Feat update card design

### LINKED ISSUE #117: [FEATURE]: Update Deal Card Design
Design of deal cards should be updated to match the figma design.

Should display:

- name
- image
- coupon percentage (overlaid on image)
- "learn more" link should be replaced with "coupon code: <code> 
- card should link directly to the deal itself
- should display start through end dates
-  should updated existing `Deal.tsx` component and rename to `DealCard.tsx`

CleanShot 2024-05-10 at 11 50 56

### PR DESCRIPTION
**Pull request by jamesqquick**
Update deal cards based on Figma design.

## Issue
Closes #117 

## Screenshot
CleanShot 2024-05-15 at 13 19 02

## Open Questions
Where do we link people when they click the card? Right now, the cards are missing some details (dates, coupon details, etc.) We need to address this in a future issue.

## PR Requirements

- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [x] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

**Review by ryandotfurrer — APPROVED** [review]
Loving the new design! This is a hell of a PR who's scope is far greater than the ticket, though 😅

**Comment by jamesqquick** [comment]
@ryandotfurrer great call! Any suggestion on what I should do? Should I:

- reword the feature/branch?
- remove code that doesn't specifically target the issue?
- something else?

**Comment by ryandotfurrer** [comment]
@jamesqquick 
> great call! Any suggestion on what I should do? 

Now I feel like you're testing me! If I were you I'd do the following:
- Add more detail to the [PR comments](https://github.com/Learn-Build-Teach/deals-for-devs/pull/126#issue-2298543353) with all the changes made
- You _could_ stash your code that is outside the scope of this issue and and apply it to a new branch that envelops all of your changes.
- I like the idea of rewording your branch but what good is a branch that is a paragraph long?

I feel like the call is ultimately up to you being the repo owner and a _far more_ senior dev than me. Speaking from my experience, I've been told off (in a nice way) for doing more work outside of the scope if the issue/ticket. That said, I know it's a very easy thing to do when you're primarily a solo dev.

What would _you_ suggest if a contributor submitted a PR that far exceeded the scope of their ticket?

**Review by chris-nowicki — APPROVED** [review]
These changes look amazing! I am totally okay with it being above and beyond the ticket @ryandotfurrer ... hehe

This really does look amazing, James!

**Pull request merged**
