### PR TITLE
README Updates

### PR DESCRIPTION
**Pull request by joshmedeski**
## Description
Did an audit on the README and have some proposed changes to improve communication.

## Screenshot

https://contrib.rocks offers a more simple solution that stays up-to-date.

SCR-20240508-kwvi

## PR Requirements
- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [x] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

**Comment by jamesqquick** [comment]
@chris-nowicki @CBID2 any thoughts on using this route to display contributors? It doesn't require any manual action to include them. It just generates the contributor section based on code contributors automatically. It doesn't give us the level of granularity that our current one has. I'm open to suggestions

**Comment by CBID2** [comment]
Looks cool! 😊

**Comment by joshmedeski** [comment]
Do you want me to remove the `.all-contributorsrc` file in this PR too?

**Comment by chris-nowicki** [comment]
> @chris-nowicki @CBID2 any thoughts on using this route to display contributors? It doesn't require any manual action to include them. It just generates the contributor section based on code contributors automatically. It doesn't give us the level of granularity that our current one has. I'm open to suggestions

Love it! Looks good to me and much easier 🚀

**Pull request closed without merging**
